# PowerScreen entry for the Moonraker/Fluidd Update Manager.

[update_manager powerscreen]
type: zip
channel: beta
repo: borferkic/K1C-CFS-POWER-SCREEN
path: /usr/data/powerscreen
managed_services: powerscreen
